# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from pathlib import Path

# 変数
base_url = "https://192.168.56.109"
base_save_folder = "screenshots/"
base_download_dir = "downloads/"
base_secret_url_dir = 'secret_url/'
test_account_mail = "contributor@weko-selenium.jp"
test_account_password = "uspass123"
guest_mail = "guest@weko-selenium.jp"
guest_password = "Aa12345-"

term_title = 'Test Terms and Conditions Title'
edited_term_title = 'Edited ' + term_title

application_for_use_error_msg = 'This data is not available for this user'
cannot_download_msg = 'Could not download file.'

users = {
    'System': {
        'mail': 'sysadmin@weko-selenium.jp',
        'password': 'uspass123'
    },
    'Repository': {
        'mail': 'repoadmin@weko-selenium.jp',
        'password': 'uspass123'
    },
    'Community': {
        'mail': 'comadmin@weko-selenium.jp',
        'password': 'uspass123'
    },
    'RegCon': {
        'mail': 'reg-contributor@weko-selenium.jp',
        'password': 'uspass123'
    },
    'NoRegCon': {
        'mail': 'noreg-contributor@weko-selenium.jp',
        'password': 'uspass123'
    },
    'PrxRegCon': {
        'mail': 'prxreg-contributor@weko-selenium.jp',
        'password': 'uspass123'
    },
    'General': {
        'mail': 'general@weko-selenium.jp',
        'password': 'uspass123'
    }
}

item_name_dic = {
    'open_access': 'B1_オープンアクセス',
    'restricted_access': 'B2_制限公開',
    'before_publish': 'B3_公開前',
    'after_publish': 'B4_公開後',
    'private': 'B5_非公開',
    'scenario_1': 'テストシナリオ1',
    'scenario_2': 'テストシナリオ2',
    'scenario_3': 'テストシナリオ3',
    'scenario_4': 'テストシナリオ4',
    'scenario_5': 'テストシナリオ5',
    'scenario_6': 'テストシナリオ6'
}

mail_subjects = {
    'request_for_register': '利用報告の登録のお願い／Request for register Data Usage Report',
    'request_for_approval':
        'データ利用申請の承認のお願い（ログインユーザー向け）／Request for Approval of Application for Use （for logged in users）',
    'request_for_approval_for_guest':
        'データ利用申請の承認のお願い（ゲストユーザー向け）／Request for Approval of Application for Use  （for guest user）',
    'approved_application':
        '利用申請の承認のお知らせ（ログインユーザー向け）／Your application was approved  （for logged in users）',
    'approved_application_for_guest':
        '利用申請の承認のお知らせ（ゲストユーザー向け）／Guest\'s application was approved （for guest user）',
    'results_of_the_review':
        '利用申請の審査結果について（ログインユーザー向け）／The results of the review of your application  （for logged in users）',
    'results_of_the_review_for_guest':
        '利用申請の審査結果について（ゲストユーザー向け）／The results of the review of your application  （for guest user）',
    'received_application': '利用報告の受付のお知らせ／Your Application was Received',
    'register_application': '利用申請登録のご案内／Register Application for Use'
}

class SetupDriver:
    def setup_driver(self):
        options = webdriver.ChromeOptions()
        
        dldir_path = Path(base_download_dir)
        dldir_path.mkdir(exist_ok=True)
        download_dir = str(dldir_path.resolve())
        # print(download_dir)


        options.add_experimental_option("prefs", {
            "download.default_directory": download_dir,
            "plugins.always_open_pdf_externally": True
        })

        self.driver = webdriver.Remote(
            command_executor="http://selenium:4444/wd/hub", options=options
        )
        self.vars = {}

        self.driver.implicitly_wait(10)
        
        self.driver.get(base_url)
        self.driver.find_element(By.XPATH,"/html/body/div/div[2]/button[3]").click()
        self.driver.find_element(By.XPATH,"/html/body/div/div[3]/p[2]/a").click()

    def teardown_method(self):
        self.driver.quit()
